encoding: "UTF-8"
lang: zh-hant

project:
  type: book
  output-dir: _book/zht

language: _language-zh-hant.yml 

book:
  title: "框智格局：<br/><small>AI 賽局手冊</small>"
  author: "廖漢騰"
  chapters:
    - file: index.zh-hant.md
    - file: 00-02-notes-mental_fill-in.zh-hant.md
    - file: 00-03-notes-constructive_fill-in.zh-hant.md
    - file: toc.zh-hant.md         # This page will display the full TOC/Listings
    - part: "01----problematics.zh-hant.md"
      chapters:
        - 01-01-Turing_Test.zh-hant.md
        - 01-02-Chinese_Room.zh-hant.md
        - 01-03-Symbol_Grounding_Problem.zh-hant.md
        - 01-04-Frame_Problem.zh-hant.md
        - 01-05-Gestalt_Psychology.zh-hant.md
        - 01-06-Alignment_Control_Problem.zh-hant.md
        - 01-07-Language_Games.zh-hant.md


