# _quarto-en.yml
project:
  render:
    - "*.en.qmd"
format:
  html:
    grid:
      sidebar-width: 330px   # Applies exclusively to the English render
      body-width: 850px
      margin-width: 260px
      gutter-width: 1.5rem
    toc-title: "〜📖 On This Page 📑〜"
