# —📖Table of Contents📑— {.unnumbered}
* 🤗 Preface 〜  🙩 [Harnessing Intelligence: AI Game Playbook for Cognitive Scaffolding](00-01-preface.en.qmd)
* ▘ Intro ~  [❝Mental Fill-ins❞: Cognitive Shortcuts](00-02-notes-mental_fill-in.en.qmd)
* ▚ Note ~  [🙶Constructive Fill-ins🙷: Cognitive Unity of Knowledge and Action](00-03-notes-constructive_fill-in.en.qmd)
* [01 ㉄](01----problematics.en.qmd)　AI Problematics
	* **1.1** 🎭🗪 [Turing Test](01-01-Turing_Test.en.qmd)
	* **1.2** 🧱🗣️ [Chinese Room](01-02-Chinese_Room.en.qmd)
	* **1.3** 🔤⚓ [Symbol Grounding Problem](01-03-Symbol_Grounding_Problem.en.qmd)
	* **1.4** 🖼️⏱️ [Frame Problem](01-04-Frame_Problem.en.qmd)
	* **1.5** 👁️⯊ [Gestalt Psychology](01-05-Gestalt_Psychology.en.qmd)
	* **1.6** 🎯🛡️ [AI Alignment & Control Problem](01-06-Alignment_Control_Problem.en.qmd)
	* **1.7** 🗫🎲 [Language Games](01-07-Language_Games.en.qmd)
* [02 🎏🏮](02----schools_paradigms.en.qmd)　Schools & Paradigms
	* **2.1** 🎏🏛️ [Symbolic AI / Logicism](02-01-symbolic_ai.en.qmd)
	* **2.2** 🎏🌀 [Statistical AI](02-02-statistical_ai.en.qmd)
	* **2.3** 🎏🧠 [Neuro-Symbolic AI](02-03-neurosymbolic_ai.en.qmd)
	* **2.4** 🪙🫣 [AGI](02-04-agi.en.qmd)
	* **2.5** 🏮🧬 [Connectionism](02-05-connectionism.en.qmd)
	* **2.6** 🏮💪 [Behaviorism](02-06-behaviorism.en.qmd)
	* **2.7** 😵‍💫🧞‍♀️ [Large Language Models](02-07-large_language_models.en.qmd)
* [03 🏛️](03----symbolic_ai.en.qmd)　Symbolic AI
	* **3.1** 🏛️⊨∴ [Formal Logic](03-01-formal_logic.en.qmd)
	* **3.2** 🏛️🤖💬 [Automatic Dialogue Systems](03-02-automatic_dialogue_systems.en.qmd)
	* **3.3** 🏛️🎁🧠 [Expert Systems](03-03-expert_systems.en.qmd)
	* **3.4** 🏛️🛠️🏗️ [Knowledge Representation](03-04-knowledge_representation.en.qmd)
	* **3.5** 🏛️🕸💡 [Knowledge Graphs](03-05-knowledge_graph.en.qmd)
	* **3.6** 🏛️🌐🔗 [Semantic Web](03-06-semantic_web.en.qmd)
	* **3.7** 🏛️🌌🗺️ [Ontology](03-07-ontology.en.qmd)
* [04 🌀](04----statistical_ai.en.qmd) Statistical AI
	* **4.1** 🌀🎲🌿 [Probabilistic Association](04-01-probabilistic_association.en.qmd)
	* **4.2** 🌀🧞‍♀️🗪 [LLM-based Chatbots](04-02-llm_chatbots.en.qmd)
	* **4.3** 🌀🪢🧠 [Neural Networks](04-03-neural_networks.en.qmd)
	* **4.4** 🌀🛠️🤏 [Feature Engineering](04-04-feature_engineering.en.qmd)
	* **4.5** 🌀🤖📦 [Machine Learning Models](04-05-machine_learning_models.en.qmd)
	* **4.6** 🌀🌐🔗 [LLM WebAssembly](04-06-llm_webassembly.en.qmd)
	* **4.7** 🌀🌌▦ [Vector Space](04-07-vector_space.en.qmd)
* [05 ☸](05----ai_orientations.en.qmd) AI Orientations
	* **5.1** ☸🎯 **[Task-oriented AI](05-01-oriented_task.en.qmd)**
	* **5.2** ☸🛠 **[Tool-oriented AI](05-02-oriented_tool.en.qmd)**
	* **5.3** ☸🤖 **[Agent-oriented AI](05-03-oriented_agent.en.qmd)**
	* **5.4** ☸🤝 **[Collaborative AI / Human-Centered AI](05-04-oriented_collaborative.en.qmd)**
	* **5.5** ☸⚖️ **[Governance-oriented AI](05-05-oriented_governance.en.qmd)**
* [06 ❖](06----analytics_decisions.en.qmd) Analytics & Decisions
	* **6.1** 🟡😷🩺 [Diagnostic Analysis](06-01-analysis_diagnostic.en.qmd)
	* **6.2** 🟠🤠🔮 [Predictive Analysis](06-02-analysis_predictive.en.qmd)
	* **6.3** 🔴🧐🧭 [Prescriptive Analysis](06-03-analysis_prescriptive.en.qmd)
	* **6.4** 🔵🤓📘 [Descriptive Analysis](06-04-analysis_descriptive.en.qmd)
	* **6.5** 🟣🙀🎨 [Generative AI](06-05-analysis_generative.en.qmd)
	* **6.6** 🔁😽🪄  [Decision-making Algorithm](06-06-decision_making_algorithm.en.qmd)
* [07 🏆](07----game_ai.en.qmd) Game AI
	* **7.1** 🏆🐭🗺️ [IEEE Micromouse](07-01-ieee_micromouse.en.qmd)  
	* **7.2** 🏆🕹️👾 [Atari DQN](07-02-atari_dqn.en.qmd)
	* **7.3** 🏆⚪⚫ [AlphaGo](07-03-alphago.en.qmd)
	* **7.4** 🏆🃏💰 [Poker AI](07-04-poker_ai.en.qmd)
	* **7.5** 🏆🧙‍♂🥷 [OpenAI Five](07-05-openai_five.en.qmd)
	* **7.6** 🏆🐺🧑‍🌾 [Werewolf AI](07-06-werewolf_ai.en.qmd)
	* **7.7** 🏆🪖⚔️ [Battlefield Simulation](07-07-complex_strategic_simulation.en.qmd)
* [08 🦾](08----embodied_ai.en.qmd) Embodied AI
	* **8.1** 🦾🎬🔋 [Robotics & Physical Actuation](08-01-robotics_and_physical_actuation.en.qmd)（Robotics & Physical Actuation）
	* **8.2** 🦾📡🌡️ [Perception & Environment](08-02-perception_and_environment.en.qmd)
	* **8.3** 🦾🔄🖼️ [Adaptive Robotics](08-03-adaptive_robotics.en.qmd)
	* **8.4** 🦾🤝💪 [Human-Robot Interaction, HRI](08-04-human_robot_interaction.en.qmd)
	* **8.5** 🦾🛡️🚨 [Robot Safety & Robustness](08-05-robot_safety_and_robustness.en.qmd)
	* **8.6** 🦾🧭🎯 [Task & Goal Planning](08-06-robot_tasks_and_goals.en.qmd)
* [09 📐](09----ai_math.en.qmd) Maths for AI
	* **9.1** 🤝🚿 [Collaborative Filtering](09-01-collaborative_filtering.en.qmd)
	* **9.2** 📉⛰️ [Steepest Descent Method](09-02-steepest_descent_method.en.qmd)
	* **9.3** 🔮🕸️ [Bayesian Network](09-03-bayesian_network.en.qmd)
	* **9.4** 🧹🧩 [Sparse Modeling](09-04-sparse_modeling.en.qmd)
	* **9.5** ⛓️🔄 [Markov Modeling](09-05-markov_modeling.en.qmd)
	* **9.6** 🌲🧭 [Monte Carlo Tree Search, MCTS](09-06-monte_carlo_tree_search.en.qmd)
	* **9.7** 🧠⚡ [Hebb’s Rule](09-07-hebb_rule.en.qmd)
	* **9.8** 🧮💰 [Multi-Agent Payoff Matrix](09-08-multi_agent_payoff_matrix.en.qmd)
* [10 🌉](10----ai_engineering.en.qmd) AI Engineering
	* **10.1** 🌉🔗🌐 [API/MCP](10-01-API_MCP.en.qmd)
	* **10.2** 🌉🤖🚨 [Agent Reliability & Evaluation](10-02-agent_reliability_evaluation.en.qmd)
	* **10.3** 🌉❔📌 [Prompt Engineering](10-03-prompt_engineering.en.qmd)
	* **10.4** 🌉🔗📒 [Retrieval-Augmented Generation](10-04-retrieval_augmented_generation.en.qmd)
	* **10.5** 🌉🪟🧭 [Context Engineering](10-05-context_engineering.en.qmd)
	* **10.6** 🎁🌱🚀 [AI Product Management](10-06-AI_PM.en.qmd)
* ▙ [Bibliography](references.en.qmd)
* **▜ Appendices & Notes**：
	* A. 💪[Action](appendix-action.en.qmd)："Action Concerto" 〜 Focusing on **Verbs** 
	* B. 🧠[Brain](appendix-brain.en.qmd)："Naming Intelligence" 〜 Focusing on **Nouns** 
	* C. 🪜[Cognitive Capacity](appendix-cognitive_capacity.en.qmd)："Framing Scaffolding" 〜 Focusing on **Nouns ➕ Verbs** 
	* D. ⚙[MCP/API Classification](appendix-MCP_API.en.qmd)
	* E. 🌌[Mindmap](appendix-mindmap.en.qmd)
	* F. 📔[Cover, Back Cover, and Spine](cover_back.en.qmd)
	* G. 🔖[Glossary](appendix-glossary.en.qmd)
		* 🧠 [Cognitive Fill-in](00-03-notes-constructive_fill-in.en.qmd) 🐸🐘🧘
		* 🧠🧞‍♀️ [〜Language Game Mental Fill-in Engines](00-02-notes-mental_fill-in.en.qmd)
		* 🪜👨‍👩‍👧‍👦 〜Parent's Edition: Legacy appendix-cognitive_capacity.en.qmd#parents
		* 🪜🧘 〜Learner's Edition: Setting Roots appendix-cognitive_capacity.en.qmd#learners      